# Dockerfile dev pour Frontend
FROM node:22
WORKDIR /app

# Installer les dépendances
COPY package*.json ./
RUN npm ci

# Copier le code source
COPY . .

# Expose port
EXPOSE 4200

# Lancer Angular en mode dev (écoute 0.0.0.0 pour Docker)
CMD ["npm", "start"]
