version: '3.8'

services:
  db:
    image: mariadb:10.11
    container_name: btp_db_container
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ""         # root sans mot de passe
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"  # autorise mot de passe vide
      MYSQL_DATABASE: btp_db           # nom de la base créée automatiquement
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

  backend:
    build:
      context: ./Backend
      dockerfile: DockerFile
    container_name: btp_backend
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://db:3306/btp_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ""    # vide pour correspondre au root sans mot de passe
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8080:8080"
    restart: unless-stopped

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    container_name: btp_frontend
    depends_on:
      - backend
    ports:
      - "4200:80"
    restart: unless-stopped

volumes:
  db_data:
