# Dockerfile dev pour Backend
FROM maven:3.9.6-eclipse-temurin-21
WORKDIR /app

# Copie uniquement pom.xml pour profiter du cache
COPY pom.xml .

# Installer les dépendances
RUN mvn dependency:go-offline

# Copier le code source
COPY src ./src

# Expose port
EXPOSE 8080

# Lancer Spring Boot en mode dev
CMD ["mvn", "spring-boot:run"]
